options:
  # Juju Lint options.
  lint-config:
    type: string
    default: "/usr/share/juju-lint/contrib/canonical-openstack-rules.yaml"
    description: |
      Juju Lint rules file path.
  lint-override:
    type: string
    default: ""
    description: |
      'Hash separated subordinate rule overrides. (Syntax:
      "<name>:<location>#<name>:<location>")'
  lint-loglevel:
    type: string
    default: "INFO"
    description: |
      'Logging level, either "CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", or
      "NOTSET".'
  lint-logfile:
    type: string
    default: ""
    description: |
      Log file path.
  lint-frequency:
    type: int
    default: 30
    description: |
      Specifies how often Juju Lint is run, in minutes.

  # Juju model connection options.
  controller-endpoint:
    type: string
    default:
    description: |
      'A controller API endpoint. (Syntax: "<hostname>:<port>")'
  controller-username:
    type: string
    default:
    description: |
      A controller user's username.
  controller-password:
    type: string
    default:
    description: |
      The respective controller user's password.
  controller-cacert:
    type: string
    default:
    description: |
      The controller CA certificate.
  model-uuid:
    type: string
    default:
    description: |
      The model UUID.

  # layer:apt options.
  install_sources:
    default: "ppa:juju-linters/ppa"
  install_keys:
    default: "null"
